### ISSUE TITLE
Source/variables for details

### ISSUE THREAD

**Issue by countnazgul** [Informatiqal/automatiqal-cli#92]
In some cases some of the `details` properties are dynamic (aka depends on result of previous task). For example:

- create brand new virtual proxy
- link the new virtual proxy to an existing proxy service

In reality the `link` process is actually update of the proxy service. The data send during the update process (related to VP) is to add the id(s) of the virtual proxy, that is going to be linked, to `virtualProxies` property. The `virtualProxies` property accepts an string array of VP id(s). And in our case the id of the new VP is unknown until the VP is actually created.

The below example shows where the new VP id should be added

```yaml
  - name: Create VP
    operation: virtualProxy.create
    details:
      prefix: test
      description: Testing
      sessionCookieHeaderName: X-Qlik-Session-Test
  - name: Add virtual proxy to proxy service
    operation: proxy.update
    filter: serverNodeConfiguration.proxyEnabled eq True and serverNodeConfiguration.name ne 'Central'
    details:
      virtualProxies:
        - ???
```

For this case there should be a way to pass the result of `Create VP` to the `details.virtualProxies`. There is already `${...}` syntax that is used for the variables replacement. Something similar should be use in this instance as well:

- `^{Create VP}`
- `^^{Create VP}`
- `$${Create VP}`

Similarly to `source` property only the `id` properties will be extracted from the "source" task
